version: '3'
services:
  naviportfolio:
    container_name: naviportfolio-container
    build:
      context: .
      dockerfile: dockerfile
      target: build
    ports:
      - 8082:80
    networks:
      - mainproxy
networks:
  mainproxy:
    external:
      name: mainproxy
